### ISSUE TITLE
Not saving any images?

### ISSUE THREAD

**Issue by Zaanmedia** [mosets/profilepicture#12]
I have tried to implement this in to my theme and the code provided works fine!

Somehow when i try to upload an image/profile picture i select a image and nothing happend! Than i click save... than you see a broken image look at the source and than you see a image name! Only there are nowhere profile pictures to be found in the folders? 

I hope someone know this issue and have a solution for me to fix this.

Thanks

**Comment by Zaanmedia** [comment]
Thanks for releasing 2.0.3 it works fine by now! Thanks for this awesome plugin keep up the good work!

**Comment by cheryeong** [comment]
Glad you find it helpful!
