### ISSUE TITLE
Change Picturesizes

### ISSUE THREAD

**Issue by janstieler** [mosets/profilepicture#13]
Hi,
is there a possibility to change the picturesizes of this plugin?
Standard are squared images and I want to use mixed imagesizes.
158px * 158px (thumbnails) and 436px * 292px (Bigger Images).

Cheers

**Comment by mierza** [comment]
Hi ,
i'm with you ✋🏻
I need to change the size from which file i can change it without make any issue?

**Comment by cheryeong** [comment]
Currently the only way to change this would be to edit the PHP constant at this file:

**/libraries/profilepicture/profilepicture.php**

LINE 21-22:

`
DEFINE('PROFILEPICTURE_SIZE_50', 50);
DEFINE('PROFILEPICTURE_SIZE_200', 200);
`

@janstieler 

In your case, the code would like something like this:


`
DEFINE('PROFILEPICTURE_SIZE_50', 158);
DEFINE('PROFILEPICTURE_SIZE_200', 436);
`

**Comment by janstieler** [comment]
HI @cheryeong,
I have tried to change it on the way you wrote. But if I change only the picture size it will not work further.
The plugin will not copy the images in the both sizefolders. 

I have no idea why?
Than I change only the size of the recalculated images but not the path or the constant.
