### ISSUE TITLE
The profileimage is not shown only the placeholder

### ISSUE THREAD

**Issue by janstieler** [mosets/profilepicture#14]
Hi,
I have uploaded an jpg to an user.
Now I want to show this in the author.php layoutfile. For this I have created an override with this code:

https://gist.github.com/janstieler/9927e4b54c538c762fd6358925036d7e

But on the frontend it will show me only the placeholderimage and not the uploaded one.

What do I'm wrong?

Kind regards.

**Comment by mierza** [comment]
Hi
I give you solution check your link on Github and tell me result
and also i request for whole code of the author.php or provide me the exactly folder on joomla the file is located

Best Regards,
Mierza

**Comment by janstieler** [comment]
Good evening,
thanks for your reply!
Sorry but nothing of this worked for me.
The original code is located in this folder: https://github.com/joomla/joomla-cms/blob/staging/layouts/joomla/content/info_block/author.php

Kind Regards,
Jan

**Comment by mierza** [comment]
Hi ,
I will check and give you the result

Best Regards ,
Mierza

**Comment by mierza** [comment]
Just to inform you
We must get the 
author(who create item) ID
Not the user id because user id is who login to joomla
So i will find the author id and come back to you as soon as possible
If i'm not wrong , this Lib. Of joomla content , right?

**Comment by janstieler** [comment]
Hi,
okay the creator Id you will get with $displayData['item']->created_by
But also if I put the ID directly inside new ProfilePicture(897); It will display only the filler image.
Really, I'm out if ideas!

**Comment by mierza** [comment]
Are you sure the user with ID 897 has picture
Can you check it and tell me

**Comment by janstieler** [comment]
Yes it has.
I found out why it not will be displayed. The image has got a second suffix (.jpg) after I uploaded it.

I think there is a big-bug with the upload function. Because if I upload a picture I see a standard html-placeholder in the backend but not the picture himself and in the folder media/plg_user_profilepicture/images is no image saved.
Need I special writingrules on this folder?

The testingimage I have uploaded through ftp and named with the right token. thats the reson why i get this now shown. But on other users I have the problem I wrote before furthermore.

Cheers

**Comment by mierza** [comment]
Please Go To
[your Joomla folder]/plugins/user/profilepicture/profilepicture.php

In Exactly File: profilepicture.php

Change this code:
jimport('mosets.profilepicture.profilepicture');

To:
jimport('profilepicture.profilepicture');

Let me know if its work

Best Regards,
Mierza

**Comment by darmolloy** [comment]
Hi,
I left this solution on your thread linked above.
https://github.com/joomla/joomla-cms/blob/staging/layouts/joomla/content/info_block/author.php

I used the following line of code and it works for me:

$profilepicture = new ProfilePicture($displayData['item']->created_by); //passes in the author ID

instead of what you used:

$profilepicture = new ProfilePicture($user->get('id')); // this will pass in the currently logged in user ID which is not what you want.

Note:
The following two lines should be removed from the author.php file that you linked to:

//Get the current user object
$user = JFactory::getUser();

Regards,
Darran

**Comment by janstieler** [comment]
Hi,
so now how I see everything looks good now.
Thank you very much for everybody to help me, especially @mierza !

Best regards,
Jan

**Comment by mierza** [comment]
Happy to know its solve
Best Regards
Mierza
