### ISSUE TITLE
Still working?

### ISSUE THREAD

**Issue by wderuijter** [mosets/profilepicture#16]
@cheryeong is this package still working?

I notice the link in de JED says:
http://extensions.joomla.org/extensions/extension/clients-a-communities/user-management/profile-picture
```
Profile Picture

This extension has been unpublished for the following reason:
UR14: Non-Compatible With Supported Versions
View error codes
```

**Comment by cheryeong** [comment]
Thanks for the heads up. The JED listing was attached with an older version with the bug. I've updated the information on JED and raised a support ticket to have it published back.

In the mean time, the latest current version is 2.0.3 and you can download it here:

https://github.com/mosets/profilepicture/releases

**Comment by wderuijter** [comment]
Thanks!
