### ISSUE TITLE
Attempting to load an image of unsupported type JPG

### ISSUE THREAD

**Issue by keep** [mosets/profilepicture#2]
I can't upload any JPG even from backend or frontend.
The error message is: Attempting to load an image of unsupported type JPG.
I think the problem is in the line 138 of profilepicture.php:
$profilepicture = new JImage($files['tmp_name']['profilepicture']['file']);

**Comment by cheryeong** [comment]
Closing this issue. Please create a new issue with a sample JPG if this affects the latest version of Joomla.
