### ISSUE TITLE
Image fails to load on windows

### ISSUE THREAD

**Issue by andykirk** [mosets/profilepicture#3]
Hi,

Testing on a windows localhost fails to load the images.
This is due to unnecessary us of DS in JFormFieldProfilePicture (profilepicture.php line 55). The 'path' for the image is actually a uri, so will always need a '/' and is not platform dependant.

Replace '.DS.' with just / will fix this.
I believe this is the issue referred to by a certain user in the comments for this extension on the JED.

PS

Great extension, by the way - nice and simple.
Would be useful to have settings to change the size(s) of the pictures, and a possible 'opt out' of inline styling for the front end allow better control for templates.

I may fork this and do these myself if that's ok?

Thanks

**Comment by cheryeong** [comment]
This should be fixed in 1d9aa81e0fd4dea7f5b170285da5c3c04ed8f477.
